{
 "title": "Tesla API",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Battery % Charged",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "percentage_charged", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Battery % Charged",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "percentage_charged", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Battery Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "total_pack_energy", "legendFormat": "__auto" },
    { "expr": "energy_left", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Battery Charging / Discharging",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "battery_power", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Battery Charging vs Dicharging",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg_over_time(battery_power[10m])",
     "legendFormat": "battery power"
    },
    {
     "expr": "avg_over_time(solar_power[10m])",
     "legendFormat": "solar power"
    }
   ]
  },
  {
   "title": "Power Consumption vs Generation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "avg_over_time(load_power[10m])", "legendFormat": "consumed" },
    {
     "expr": "avg_over_time(solar_power[10m])",
     "legendFormat": "generated"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "load_power", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Power Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "grid_power", "legendFormat": "__auto" },
    { "expr": "battery_power", "legendFormat": "__auto" },
    { "expr": "solar_power", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "grid_power", "legendFormat": "__auto" },
    { "expr": "solar_power", "legendFormat": "__auto" },
    { "expr": "battery_power", "legendFormat": "__auto" }
   ]
  }
 ]
}